# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubyfca}
  s.version = "0.2.7"
  s.required_ruby_version = ">=1.8.6"
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoichiro Hasebe", "Kow Kuroda"]
  s.date = %q{2009-09-14}
  s.default_executable = %q{rubyfca}
  s.description = %q{Command line Formal Concept Ananlysis (FCA) tool written in Ruby}
  s.email = %q{yohasebe@gmail.com}
  s.executables = ["rubyfca"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rubyfca",
     "lib/ruby_graphviz.rb",
     "lib/rubyfca.rb",
     "lib/trollop.rb",
     "rubyfca.gemspec",
     "test/rubyfca_test.rb",
     "test/test_data.cxt",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/yohasebe/rubyfca}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Command line Formal Concept Analysis (FCA) tool written in Ruby}
  s.test_files = [
    "test/rubyfca_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
